cha = input("ป้อนสายอักขระ : ")
print("-----------------------------------")
print("อักขระ A มีจำนวน ",cha.count("A")," ตัว")
print("อักขระ B มีจำนวน ",cha.count("B")," ตัว")
print("อักขระอื่น ๆ มีจำนวน ",len(cha)-(cha.count("A")+cha.count("B"))," ตัว")